version: '3.4'
services:
  web:
    build: 
      target: vscode
    image: freqtradeorg/frequi:vscode
    volumes:
      - "/home/${USER}/.ssh:/home/dev/.ssh:ro"
      - "/home/${USER}/.gitconfig:/home/dev/.gitconfig:ro"
      - frequi-bashhistory:/home/dev/commandhistory
      - frequi-vscode-server:/home/dev/.vscode-server
      - frequi-server-insiders:/home/dev/.vscode-server-insiders

volumes:
  frequi-bashhistory:
  frequi-vscode-server:
  frequi-server-insiders: