version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    allowed_updates:
    - match:
        update_type: "all"
    target_branch: "master"

  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    allowed_updates:
    - match:
        update_type: "all"
