name: FreqUI CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2

    - name: npm install
      uses: bahmutov/npm-install@v1

    - name: Run Lint
      run: |
        yarn lint-ci
