name: FreqUI CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2-beta

    - run: yarn install

    - name: Run Lint
      run: yarn lint-ci

    - name: Run Tests
      run: yarn test:unit

    - name: Build build
      run: yarn build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: FreqUI-dist
        path: |
          dist
          !dist/**/*.md
        retention-days: 10
